### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by DragzDA69** [jcarbelbide/togcrowdsourcing.com#1]
It appears the website is down and therefore plugins and/or api endpoints are not working.

**Comment by jcarbelbide** [comment]
Thank you for opening this and attempting to reach me! Sorry that it has taken so long to resolve this, but the service should be back up. Let me know if problems persist. I've fixed notifications and will be adding a monitor for when the site goes down in the future so I'm notified immediately

**Comment by DragzDA69** [comment]
Thanks for getting to this so quickly! :)

**Comment by jcarbelbide** [comment]
Appreciate the kind words, but it definitely took much longer than it should have!
